/**
*	Auto generate
**/

//todo define
var resImg = {
	
	BUTTON__BACK_BTN_PNG: "res/button/back_btn.png",
	BUTTON__BTN_BLUE_0_PNG: "res/button/btn_blue_0.png",
	BUTTON__BTN_BLUE_1_PNG: "res/button/btn_blue_1.png",
	BUTTON__BTN_ORANGE_0_PNG: "res/button/btn_orange_0.png",
	BUTTON__BT_CHON_PNG: "res/button/bt_chon.png",
	BUTTON__BUTTON_BROWN_0_PNG: "res/button/button_brown_0.png",
	BUTTON__BUTTON_BUM_PNG: "res/button/button_bum.png",
	BUTTON__BUTTON_GREEN_0_PNG: "res/button/button_green_0.png",
	BUTTON__BUTTON_GREEN_1_PNG: "res/button/button_green_1.png",
	BUTTON__BUTTON_GREEN_2_PNG: "res/button/button_green_2.png",
	BUTTON__BUTTON_GREEN_3_PNG: "res/button/button_green_3.png",
	BUTTON__BUTTON_QUICKCOMPLETE_PNG: "res/button/button_QuickComplete.png",
	BUTTON__BUTTON_RECIEVEGIFT_PNG: "res/button/button_recieveGift.png",
	BUTTON__BUTTON_YELLOW_0_PNG: "res/button/button_yellow_0.png",
	BUTTON__BUTTON_YELLOW_1_PNG: "res/button/button_yellow_1.png",
	BUTTON__BUTTON_YELLOW_2_PNG: "res/button/button_yellow_2.png",
	BUTTON__BUTTON_YELLOW_3_PNG: "res/button/button_yellow_3.png",
	BUTTON__CLOSENORMAL_PNG: "res/button/CloseNormal.png",
	BUTTON__CLOSESELECTED_PNG: "res/button/CloseSelected.png",
	BUTTON__X_PNG: "res/button/x.png",
	BUTTON__X2_PNG: "res/button/x2.png",
	BUTTON__X3_PNG: "res/button/x3.png",
	DEFAULT__BUTTON_DISABLE_PNG: "res/Default/Button_Disable.png",
	DEFAULT__BUTTON_NORMAL_PNG: "res/Default/Button_Normal.png",
	DEFAULT__BUTTON_PRESS_PNG: "res/Default/Button_Press.png",
	DEFAULT__CHECKBOXNODE_DISABLE_PNG: "res/Default/CheckBoxNode_Disable.png",
	DEFAULT__CHECKBOXNODE_NORMAL_PNG: "res/Default/CheckBoxNode_Normal.png",
	DEFAULT__CHECKBOX_DISABLE_PNG: "res/Default/CheckBox_Disable.png",
	DEFAULT__CHECKBOX_NORMAL_PNG: "res/Default/CheckBox_Normal.png",
	DEFAULT__CHECKBOX_PRESS_PNG: "res/Default/CheckBox_Press.png",
	DEFAULT__IMAGEFILE_PNG: "res/Default/ImageFile.png",
	DEFAULT__LOADINGBARFILE_PNG: "res/Default/LoadingBarFile.png",
	DEFAULT__SPRITE_PNG: "res/Default/Sprite.png",
	NUMBER__STYLE1__0_PNG: "res/number/style1/0.png",
	NUMBER__STYLE1__1_PNG: "res/number/style1/1.png",
	NUMBER__STYLE1__2_PNG: "res/number/style1/2.png",
	NUMBER__STYLE1__3_PNG: "res/number/style1/3.png",
	NUMBER__STYLE1__4_PNG: "res/number/style1/4.png",
	NUMBER__STYLE1__5_PNG: "res/number/style1/5.png",
	NUMBER__STYLE1__6_PNG: "res/number/style1/6.png",
	NUMBER__STYLE1__7_PNG: "res/number/style1/7.png",
	NUMBER__STYLE1__8_PNG: "res/number/style1/8.png",
	NUMBER__STYLE1__9_PNG: "res/number/style1/9.png",
	NUMBER__STYLE2__0_PNG: "res/number/style2/0.png",
	NUMBER__STYLE2__1_PNG: "res/number/style2/1.png",
	NUMBER__STYLE2__2_PNG: "res/number/style2/2.png",
	NUMBER__STYLE2__3_PNG: "res/number/style2/3.png",
	NUMBER__STYLE2__4_PNG: "res/number/style2/4.png",
	NUMBER__STYLE2__5_PNG: "res/number/style2/5.png",
	NUMBER__STYLE2__6_PNG: "res/number/style2/6.png",
	NUMBER__STYLE2__7_PNG: "res/number/style2/7.png",
	NUMBER__STYLE2__8_PNG: "res/number/style2/8.png",
	NUMBER__STYLE2__9_PNG: "res/number/style2/9.png",
	NUMBER__STYLE3__0_PNG: "res/number/style3/0.png",
	NUMBER__STYLE3__1_PNG: "res/number/style3/1.png",
	NUMBER__STYLE3__2_PNG: "res/number/style3/2.png",
	NUMBER__STYLE3__3_PNG: "res/number/style3/3.png",
	NUMBER__STYLE3__4_PNG: "res/number/style3/4.png",
	NUMBER__STYLE3__5_PNG: "res/number/style3/5.png",
	NUMBER__STYLE3__6_PNG: "res/number/style3/6.png",
	NUMBER__STYLE3__7_PNG: "res/number/style3/7.png",
	NUMBER__STYLE3__8_PNG: "res/number/style3/8.png",
	NUMBER__STYLE3__9_PNG: "res/number/style3/9.png",
	NUMBER__STYLE3__DOT_PNG: "res/number/style3/dot.png",
	NUMBER__STYLE3__MINUS_PNG: "res/number/style3/minus.png",
	NUMBER__STYLE3__PLUS_PNG: "res/number/style3/plus.png",
	NUMBER__STYLE4__1_PNG: "res/number/style4/1.png",
	NUMBER__STYLE4__2_PNG: "res/number/style4/2.png",
	NUMBER__STYLE4__3_PNG: "res/number/style4/3.png",
	NUMBER__STYLE4__4_PNG: "res/number/style4/4.png",
	NUMBER__STYLE4__5_PNG: "res/number/style4/5.png",
	NUMBER__STYLE4__6_PNG: "res/number/style4/6.png",
	NUMBER__STYLE4__7_PNG: "res/number/style4/7.png",
	NUMBER__STYLE4__8_PNG: "res/number/style4/8.png",
	PARTICLE__ELECTRICPOINT1_PNG: "res/particle/ElectricPoint1.png",
	PARTICLE__PARTICLE__FX_2_PNG: "res/particle/Particle/fx_2.png",
	PARTICLE__PARTICLE__FX_3_PNG: "res/particle/Particle/fx_3.png",
	PARTICLE__PARTICLE__FX_4H_PNG: "res/particle/Particle/fx_4h.png",
	PARTICLE__PARTICLE__FX_4L_PNG: "res/particle/Particle/fx_4l.png",
	PARTICLE__PARTICLE__FX_4M_PNG: "res/particle/Particle/fx_4m.png",
	PARTICLE__PARTICLE__FX_4N_PNG: "res/particle/Particle/fx_4n.png",
	PARTICLE__PARTICLE__PARTICLE_TEXTURE_PNG: "res/particle/Particle/particle_texture.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH02_PNG: "res/particle/particle3d/textures/anh02.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH03_PNG: "res/particle/particle3d/textures/anh03.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH04_PNG: "res/particle/particle3d/textures/anh04.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH05_PNG: "res/particle/particle3d/textures/anh05.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH06_PNG: "res/particle/particle3d/textures/anh06.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH09_PNG: "res/particle/particle3d/textures/anh09.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH10_PNG: "res/particle/particle3d/textures/anh10.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE01_PNG: "res/particle/particle3d/textures/bot_dice01.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE02_PNG: "res/particle/particle3d/textures/bot_dice02.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE03_PNG: "res/particle/particle3d/textures/bot_dice03.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE04_PNG: "res/particle/particle3d/textures/bot_dice04.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE05_PNG: "res/particle/particle3d/textures/bot_dice05.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE06_PNG: "res/particle/particle3d/textures/bot_dice06.png",
	PARTICLE__PARTICLE3D__TEXTURES__GOLD_PNG: "res/particle/particle3d/textures/gold.png",
	PARTICLE__PARTICLE3D__TEXTURES__LOTUS_PNG: "res/particle/particle3d/textures/lotus.png",
	PARTICLE__PARTICLE3D__TEXTURES__POINT04_PNG: "res/particle/particle3d/textures/point04.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_BUBBLE_PNG: "res/particle/particle3d/textures/pump_bubble.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_BUBBLE_BLURRED_PNG: "res/particle/particle3d/textures/pump_bubble_blurred.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_FLARE_04_PNG: "res/particle/particle3d/textures/pump_flare_04.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_SMOKE_02_PNG: "res/particle/particle3d/textures/pump_smoke_02.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_SNOW_01_PNG: "res/particle/particle3d/textures/pump_snow_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_SPARK_01_PNG: "res/particle/particle3d/textures/pump_spark_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STAR_03_PNG: "res/particle/particle3d/textures/pump_star_03.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STAR_05_PNG: "res/particle/particle3d/textures/pump_star_05.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_01_PNG: "res/particle/particle3d/textures/pump_streak_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_02_PNG: "res/particle/particle3d/textures/pump_streak_02.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_03_PNG: "res/particle/particle3d/textures/pump_streak_03.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_04_PNG: "res/particle/particle3d/textures/pump_streak_04.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_CIRCLE_PNG: "res/particle/particle3d/textures/pu_circle.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_FLARE_PNG: "res/particle/particle3d/textures/pu_flare.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_RAIN_PNG: "res/particle/particle3d/textures/pu_rain.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_RAIN_01_PNG: "res/particle/particle3d/textures/pu_rain_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__RING2_PNG: "res/particle/particle3d/textures/ring2.png",
	PARTICLE__PARTICLE3D__TEXTURES__TESTPU_PNG: "res/particle/particle3d/textures/testPU.png",
	PARTICLE__TEST_PNG: "res/particle/test.png",
	PLIST__EFF_APPEAR_FALL_DOWN__TEXTURE_PNG: "res/plist/eff_appear_fall_down/texture.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__MAINBASE_PNG: "res/resources/textures/Base/Team 1/MainBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__MAINBASED_PNG: "res/resources/textures/Base/Team 1/MainBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__SIDEBASE_PNG: "res/resources/textures/Base/Team 1/SideBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__SIDEBASED_PNG: "res/resources/textures/Base/Team 1/SideBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__MAINBASE_PNG: "res/resources/textures/Base/Team 2/MainBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__MAINBASED_PNG: "res/resources/textures/Base/Team 2/MainBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__SIDEBASE_PNG: "res/resources/textures/Base/Team 2/SideBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__SIDEBASED_PNG: "res/resources/textures/Base/Team 2/SideBaseD.png",
	RESOURCES__TEXTURES__BULLET__1_PNG: "res/resources/textures/Bullet/1.png",
	RESOURCES__TEXTURES__BULLET__2_PNG: "res/resources/textures/Bullet/2.png",
	RESOURCES__TEXTURES__BULLET__3_PNG: "res/resources/textures/Bullet/3.png",
	RESOURCES__TEXTURES__CLOCK_PNG: "res/resources/textures/clock.png",
	RESOURCES__TEXTURES__DESTINATION_POINT_PNG: "res/resources/textures/destination_point.png",
	RESOURCES__TEXTURES__DESTINATION_TOUCH_PNG: "res/resources/textures/destination_touch.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_01_PNG: "res/resources/textures/Explosion/ex1/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_02_PNG: "res/resources/textures/Explosion/ex1/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_03_PNG: "res/resources/textures/Explosion/ex1/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_04_PNG: "res/resources/textures/Explosion/ex1/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_05_PNG: "res/resources/textures/Explosion/ex1/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_06_PNG: "res/resources/textures/Explosion/ex1/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_07_PNG: "res/resources/textures/Explosion/ex1/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_08_PNG: "res/resources/textures/Explosion/ex1/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_09_PNG: "res/resources/textures/Explosion/ex1/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_10_PNG: "res/resources/textures/Explosion/ex1/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_11_PNG: "res/resources/textures/Explosion/ex1/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_12_PNG: "res/resources/textures/Explosion/ex1/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_13_PNG: "res/resources/textures/Explosion/ex1/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_14_PNG: "res/resources/textures/Explosion/ex1/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_15_PNG: "res/resources/textures/Explosion/ex1/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_16_PNG: "res/resources/textures/Explosion/ex1/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_17_PNG: "res/resources/textures/Explosion/ex1/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_18_PNG: "res/resources/textures/Explosion/ex1/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_19_PNG: "res/resources/textures/Explosion/ex1/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_20_PNG: "res/resources/textures/Explosion/ex1/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_21_PNG: "res/resources/textures/Explosion/ex1/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_22_PNG: "res/resources/textures/Explosion/ex1/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_23_PNG: "res/resources/textures/Explosion/ex1/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_24_PNG: "res/resources/textures/Explosion/ex1/ex_24.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_25_PNG: "res/resources/textures/Explosion/ex1/ex_25.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_26_PNG: "res/resources/textures/Explosion/ex1/ex_26.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_27_PNG: "res/resources/textures/Explosion/ex1/ex_27.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_28_PNG: "res/resources/textures/Explosion/ex1/ex_28.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_29_PNG: "res/resources/textures/Explosion/ex1/ex_29.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_30_PNG: "res/resources/textures/Explosion/ex1/ex_30.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_31_PNG: "res/resources/textures/Explosion/ex1/ex_31.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_32_PNG: "res/resources/textures/Explosion/ex1/ex_32.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_33_PNG: "res/resources/textures/Explosion/ex1/ex_33.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_34_PNG: "res/resources/textures/Explosion/ex1/ex_34.png",
	RESOURCES__TEXTURES__EXPLOSION__EX1__EX_35_PNG: "res/resources/textures/Explosion/ex1/ex_35.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_01_PNG: "res/resources/textures/Explosion/ex2/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_02_PNG: "res/resources/textures/Explosion/ex2/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_03_PNG: "res/resources/textures/Explosion/ex2/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_04_PNG: "res/resources/textures/Explosion/ex2/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_05_PNG: "res/resources/textures/Explosion/ex2/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_06_PNG: "res/resources/textures/Explosion/ex2/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_07_PNG: "res/resources/textures/Explosion/ex2/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_08_PNG: "res/resources/textures/Explosion/ex2/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_09_PNG: "res/resources/textures/Explosion/ex2/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_10_PNG: "res/resources/textures/Explosion/ex2/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_11_PNG: "res/resources/textures/Explosion/ex2/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_12_PNG: "res/resources/textures/Explosion/ex2/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_13_PNG: "res/resources/textures/Explosion/ex2/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_14_PNG: "res/resources/textures/Explosion/ex2/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_15_PNG: "res/resources/textures/Explosion/ex2/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_16_PNG: "res/resources/textures/Explosion/ex2/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_17_PNG: "res/resources/textures/Explosion/ex2/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_18_PNG: "res/resources/textures/Explosion/ex2/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_19_PNG: "res/resources/textures/Explosion/ex2/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_20_PNG: "res/resources/textures/Explosion/ex2/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_21_PNG: "res/resources/textures/Explosion/ex2/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_22_PNG: "res/resources/textures/Explosion/ex2/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_23_PNG: "res/resources/textures/Explosion/ex2/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_24_PNG: "res/resources/textures/Explosion/ex2/ex_24.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_25_PNG: "res/resources/textures/Explosion/ex2/ex_25.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_26_PNG: "res/resources/textures/Explosion/ex2/ex_26.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_27_PNG: "res/resources/textures/Explosion/ex2/ex_27.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_28_PNG: "res/resources/textures/Explosion/ex2/ex_28.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_29_PNG: "res/resources/textures/Explosion/ex2/ex_29.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_30_PNG: "res/resources/textures/Explosion/ex2/ex_30.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_31_PNG: "res/resources/textures/Explosion/ex2/ex_31.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_32_PNG: "res/resources/textures/Explosion/ex2/ex_32.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_33_PNG: "res/resources/textures/Explosion/ex2/ex_33.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_34_PNG: "res/resources/textures/Explosion/ex2/ex_34.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_35_PNG: "res/resources/textures/Explosion/ex2/ex_35.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_36_PNG: "res/resources/textures/Explosion/ex2/ex_36.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_37_PNG: "res/resources/textures/Explosion/ex2/ex_37.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_38_PNG: "res/resources/textures/Explosion/ex2/ex_38.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_39_PNG: "res/resources/textures/Explosion/ex2/ex_39.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_40_PNG: "res/resources/textures/Explosion/ex2/ex_40.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_41_PNG: "res/resources/textures/Explosion/ex2/ex_41.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_42_PNG: "res/resources/textures/Explosion/ex2/ex_42.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_43_PNG: "res/resources/textures/Explosion/ex2/ex_43.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_44_PNG: "res/resources/textures/Explosion/ex2/ex_44.png",
	RESOURCES__TEXTURES__EXPLOSION__EX2__EX_45_PNG: "res/resources/textures/Explosion/ex2/ex_45.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_01_PNG: "res/resources/textures/Explosion/ex3/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_02_PNG: "res/resources/textures/Explosion/ex3/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_03_PNG: "res/resources/textures/Explosion/ex3/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_04_PNG: "res/resources/textures/Explosion/ex3/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_05_PNG: "res/resources/textures/Explosion/ex3/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_06_PNG: "res/resources/textures/Explosion/ex3/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_07_PNG: "res/resources/textures/Explosion/ex3/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_08_PNG: "res/resources/textures/Explosion/ex3/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_09_PNG: "res/resources/textures/Explosion/ex3/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_10_PNG: "res/resources/textures/Explosion/ex3/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_11_PNG: "res/resources/textures/Explosion/ex3/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_12_PNG: "res/resources/textures/Explosion/ex3/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_13_PNG: "res/resources/textures/Explosion/ex3/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_14_PNG: "res/resources/textures/Explosion/ex3/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_15_PNG: "res/resources/textures/Explosion/ex3/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX3__EX_16_PNG: "res/resources/textures/Explosion/ex3/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_01_PNG: "res/resources/textures/Explosion/ex4/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_02_PNG: "res/resources/textures/Explosion/ex4/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_03_PNG: "res/resources/textures/Explosion/ex4/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_04_PNG: "res/resources/textures/Explosion/ex4/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_05_PNG: "res/resources/textures/Explosion/ex4/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_06_PNG: "res/resources/textures/Explosion/ex4/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_07_PNG: "res/resources/textures/Explosion/ex4/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_08_PNG: "res/resources/textures/Explosion/ex4/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_09_PNG: "res/resources/textures/Explosion/ex4/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_10_PNG: "res/resources/textures/Explosion/ex4/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_11_PNG: "res/resources/textures/Explosion/ex4/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_12_PNG: "res/resources/textures/Explosion/ex4/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_13_PNG: "res/resources/textures/Explosion/ex4/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_14_PNG: "res/resources/textures/Explosion/ex4/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_15_PNG: "res/resources/textures/Explosion/ex4/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_16_PNG: "res/resources/textures/Explosion/ex4/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_17_PNG: "res/resources/textures/Explosion/ex4/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_18_PNG: "res/resources/textures/Explosion/ex4/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_19_PNG: "res/resources/textures/Explosion/ex4/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_20_PNG: "res/resources/textures/Explosion/ex4/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_21_PNG: "res/resources/textures/Explosion/ex4/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_22_PNG: "res/resources/textures/Explosion/ex4/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_23_PNG: "res/resources/textures/Explosion/ex4/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_24_PNG: "res/resources/textures/Explosion/ex4/ex_24.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_25_PNG: "res/resources/textures/Explosion/ex4/ex_25.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_26_PNG: "res/resources/textures/Explosion/ex4/ex_26.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_27_PNG: "res/resources/textures/Explosion/ex4/ex_27.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_28_PNG: "res/resources/textures/Explosion/ex4/ex_28.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_29_PNG: "res/resources/textures/Explosion/ex4/ex_29.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_30_PNG: "res/resources/textures/Explosion/ex4/ex_30.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_31_PNG: "res/resources/textures/Explosion/ex4/ex_31.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_32_PNG: "res/resources/textures/Explosion/ex4/ex_32.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_33_PNG: "res/resources/textures/Explosion/ex4/ex_33.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_34_PNG: "res/resources/textures/Explosion/ex4/ex_34.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_35_PNG: "res/resources/textures/Explosion/ex4/ex_35.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_36_PNG: "res/resources/textures/Explosion/ex4/ex_36.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_37_PNG: "res/resources/textures/Explosion/ex4/ex_37.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_38_PNG: "res/resources/textures/Explosion/ex4/ex_38.png",
	RESOURCES__TEXTURES__EXPLOSION__EX4__EX_39_PNG: "res/resources/textures/Explosion/ex4/ex_39.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_01_PNG: "res/resources/textures/Explosion/ex5/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_02_PNG: "res/resources/textures/Explosion/ex5/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_03_PNG: "res/resources/textures/Explosion/ex5/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_04_PNG: "res/resources/textures/Explosion/ex5/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_05_PNG: "res/resources/textures/Explosion/ex5/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_06_PNG: "res/resources/textures/Explosion/ex5/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_07_PNG: "res/resources/textures/Explosion/ex5/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_08_PNG: "res/resources/textures/Explosion/ex5/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_09_PNG: "res/resources/textures/Explosion/ex5/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_10_PNG: "res/resources/textures/Explosion/ex5/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_11_PNG: "res/resources/textures/Explosion/ex5/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_12_PNG: "res/resources/textures/Explosion/ex5/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_13_PNG: "res/resources/textures/Explosion/ex5/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_14_PNG: "res/resources/textures/Explosion/ex5/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_15_PNG: "res/resources/textures/Explosion/ex5/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_16_PNG: "res/resources/textures/Explosion/ex5/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_17_PNG: "res/resources/textures/Explosion/ex5/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_18_PNG: "res/resources/textures/Explosion/ex5/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_19_PNG: "res/resources/textures/Explosion/ex5/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_20_PNG: "res/resources/textures/Explosion/ex5/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_21_PNG: "res/resources/textures/Explosion/ex5/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_22_PNG: "res/resources/textures/Explosion/ex5/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_23_PNG: "res/resources/textures/Explosion/ex5/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_24_PNG: "res/resources/textures/Explosion/ex5/ex_24.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_25_PNG: "res/resources/textures/Explosion/ex5/ex_25.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_26_PNG: "res/resources/textures/Explosion/ex5/ex_26.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_27_PNG: "res/resources/textures/Explosion/ex5/ex_27.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_28_PNG: "res/resources/textures/Explosion/ex5/ex_28.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_29_PNG: "res/resources/textures/Explosion/ex5/ex_29.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_30_PNG: "res/resources/textures/Explosion/ex5/ex_30.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_31_PNG: "res/resources/textures/Explosion/ex5/ex_31.png",
	RESOURCES__TEXTURES__EXPLOSION__EX5__EX_32_PNG: "res/resources/textures/Explosion/ex5/ex_32.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_01_PNG: "res/resources/textures/Explosion/ex6/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_02_PNG: "res/resources/textures/Explosion/ex6/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_03_PNG: "res/resources/textures/Explosion/ex6/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_04_PNG: "res/resources/textures/Explosion/ex6/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_05_PNG: "res/resources/textures/Explosion/ex6/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_06_PNG: "res/resources/textures/Explosion/ex6/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_07_PNG: "res/resources/textures/Explosion/ex6/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_08_PNG: "res/resources/textures/Explosion/ex6/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_09_PNG: "res/resources/textures/Explosion/ex6/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_10_PNG: "res/resources/textures/Explosion/ex6/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_11_PNG: "res/resources/textures/Explosion/ex6/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_12_PNG: "res/resources/textures/Explosion/ex6/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_13_PNG: "res/resources/textures/Explosion/ex6/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_14_PNG: "res/resources/textures/Explosion/ex6/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_15_PNG: "res/resources/textures/Explosion/ex6/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_16_PNG: "res/resources/textures/Explosion/ex6/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_17_PNG: "res/resources/textures/Explosion/ex6/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_18_PNG: "res/resources/textures/Explosion/ex6/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_19_PNG: "res/resources/textures/Explosion/ex6/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_20_PNG: "res/resources/textures/Explosion/ex6/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_21_PNG: "res/resources/textures/Explosion/ex6/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_22_PNG: "res/resources/textures/Explosion/ex6/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_23_PNG: "res/resources/textures/Explosion/ex6/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_24_PNG: "res/resources/textures/Explosion/ex6/ex_24.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_25_PNG: "res/resources/textures/Explosion/ex6/ex_25.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_26_PNG: "res/resources/textures/Explosion/ex6/ex_26.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_27_PNG: "res/resources/textures/Explosion/ex6/ex_27.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_28_PNG: "res/resources/textures/Explosion/ex6/ex_28.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_29_PNG: "res/resources/textures/Explosion/ex6/ex_29.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_30_PNG: "res/resources/textures/Explosion/ex6/ex_30.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_31_PNG: "res/resources/textures/Explosion/ex6/ex_31.png",
	RESOURCES__TEXTURES__EXPLOSION__EX6__EX_32_PNG: "res/resources/textures/Explosion/ex6/ex_32.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_01_PNG: "res/resources/textures/Explosion/ex7/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_02_PNG: "res/resources/textures/Explosion/ex7/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_03_PNG: "res/resources/textures/Explosion/ex7/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_04_PNG: "res/resources/textures/Explosion/ex7/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_05_PNG: "res/resources/textures/Explosion/ex7/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_06_PNG: "res/resources/textures/Explosion/ex7/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_07_PNG: "res/resources/textures/Explosion/ex7/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_08_PNG: "res/resources/textures/Explosion/ex7/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_09_PNG: "res/resources/textures/Explosion/ex7/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_10_PNG: "res/resources/textures/Explosion/ex7/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_11_PNG: "res/resources/textures/Explosion/ex7/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_12_PNG: "res/resources/textures/Explosion/ex7/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_13_PNG: "res/resources/textures/Explosion/ex7/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_14_PNG: "res/resources/textures/Explosion/ex7/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_15_PNG: "res/resources/textures/Explosion/ex7/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_16_PNG: "res/resources/textures/Explosion/ex7/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_17_PNG: "res/resources/textures/Explosion/ex7/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_18_PNG: "res/resources/textures/Explosion/ex7/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_19_PNG: "res/resources/textures/Explosion/ex7/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_20_PNG: "res/resources/textures/Explosion/ex7/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_21_PNG: "res/resources/textures/Explosion/ex7/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_22_PNG: "res/resources/textures/Explosion/ex7/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_23_PNG: "res/resources/textures/Explosion/ex7/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_24_PNG: "res/resources/textures/Explosion/ex7/ex_24.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_25_PNG: "res/resources/textures/Explosion/ex7/ex_25.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_26_PNG: "res/resources/textures/Explosion/ex7/ex_26.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_27_PNG: "res/resources/textures/Explosion/ex7/ex_27.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_28_PNG: "res/resources/textures/Explosion/ex7/ex_28.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_29_PNG: "res/resources/textures/Explosion/ex7/ex_29.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_30_PNG: "res/resources/textures/Explosion/ex7/ex_30.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_31_PNG: "res/resources/textures/Explosion/ex7/ex_31.png",
	RESOURCES__TEXTURES__EXPLOSION__EX7__EX_32_PNG: "res/resources/textures/Explosion/ex7/ex_32.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_01_PNG: "res/resources/textures/Explosion/ex8/ex_01.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_02_PNG: "res/resources/textures/Explosion/ex8/ex_02.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_03_PNG: "res/resources/textures/Explosion/ex8/ex_03.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_04_PNG: "res/resources/textures/Explosion/ex8/ex_04.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_05_PNG: "res/resources/textures/Explosion/ex8/ex_05.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_06_PNG: "res/resources/textures/Explosion/ex8/ex_06.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_07_PNG: "res/resources/textures/Explosion/ex8/ex_07.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_08_PNG: "res/resources/textures/Explosion/ex8/ex_08.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_09_PNG: "res/resources/textures/Explosion/ex8/ex_09.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_10_PNG: "res/resources/textures/Explosion/ex8/ex_10.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_11_PNG: "res/resources/textures/Explosion/ex8/ex_11.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_12_PNG: "res/resources/textures/Explosion/ex8/ex_12.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_13_PNG: "res/resources/textures/Explosion/ex8/ex_13.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_14_PNG: "res/resources/textures/Explosion/ex8/ex_14.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_15_PNG: "res/resources/textures/Explosion/ex8/ex_15.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_16_PNG: "res/resources/textures/Explosion/ex8/ex_16.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_17_PNG: "res/resources/textures/Explosion/ex8/ex_17.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_18_PNG: "res/resources/textures/Explosion/ex8/ex_18.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_19_PNG: "res/resources/textures/Explosion/ex8/ex_19.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_20_PNG: "res/resources/textures/Explosion/ex8/ex_20.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_21_PNG: "res/resources/textures/Explosion/ex8/ex_21.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_22_PNG: "res/resources/textures/Explosion/ex8/ex_22.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_23_PNG: "res/resources/textures/Explosion/ex8/ex_23.png",
	RESOURCES__TEXTURES__EXPLOSION__EX8__EX_24_PNG: "res/resources/textures/Explosion/ex8/ex_24.png",
	RESOURCES__TEXTURES__MAP__BACKGROUND_PNG: "res/resources/textures/Map/Background.png",
	RESOURCES__TEXTURES__MAP__BACKGROUND_4_DIRECTION_PNG: "res/resources/textures/Map/background_4_direction.png",
	RESOURCES__TEXTURES__MAP__BRICK___1_PNG: "res/resources/textures/Map/Brick 1.png",
	RESOURCES__TEXTURES__MAP__BRICK___2_PNG: "res/resources/textures/Map/Brick 2.png",
	RESOURCES__TEXTURES__MAP__BRICK___3_PNG: "res/resources/textures/Map/Brick 3.png",
	RESOURCES__TEXTURES__MAP__BRICK___4_PNG: "res/resources/textures/Map/Brick 4.png",
	RESOURCES__TEXTURES__MAP__BRICK___5_PNG: "res/resources/textures/Map/Brick 5.png",
	RESOURCES__TEXTURES__MAP__CIRCLE_WHITE_PNG: "res/resources/textures/Map/circle_white.png",
	RESOURCES__TEXTURES__MAP__CONCRETE_PNG: "res/resources/textures/Map/Concrete.png",
	RESOURCES__TEXTURES__MAP__WATER_PNG: "res/resources/textures/Map/Water.png",
	RESOURCES__TEXTURES__PARTICLE__BLACKSMOKE_PNG: "res/resources/textures/Particle/BlackSmoke.png",
	RESOURCES__TEXTURES__PARTICLE__FRAG_PNG: "res/resources/textures/Particle/Frag.png",
	RESOURCES__TEXTURES__PARTICLE__WHITESMOKE_PNG: "res/resources/textures/Particle/WhiteSmoke.png",
	RESOURCES__TEXTURES__POWERUP__AIRPLANE___1_PNG: "res/resources/textures/PowerUp/Airplane 1.png",
	RESOURCES__TEXTURES__POWERUP__AIRPLANE___2_PNG: "res/resources/textures/PowerUp/Airplane 2.png",
	RESOURCES__TEXTURES__POWERUP__AIRSTRIKE_PNG: "res/resources/textures/PowerUp/Airstrike.png",
	RESOURCES__TEXTURES__POWERUP__EMP_PNG: "res/resources/textures/PowerUp/EMP.png",
	RESOURCES__TEXTURES__PROGRESS_BG_PNG: "res/resources/textures/progress_bg.png",
	RESOURCES__TEXTURES__PROGRESS_BULE_PNG: "res/resources/textures/progress_bule.png",
	RESOURCES__TEXTURES__PROGRESS_RED_PNG: "res/resources/textures/progress_red.png",
	RESOURCES__TEXTURES__SPLASH_PNG: "res/resources/textures/Splash.png",
	RESOURCES__TEXTURES__STRINGS__BADDRAW_PNG: "res/resources/textures/Strings/BadDraw.png",
	RESOURCES__TEXTURES__STRINGS__DRAW_PNG: "res/resources/textures/Strings/Draw.png",
	RESOURCES__TEXTURES__STRINGS__STRINGTEMPLATE_PNG: "res/resources/textures/Strings/StringTemplate.png",
	RESOURCES__TEXTURES__STRINGS__TEAM1WIN_PNG: "res/resources/textures/Strings/Team1Win.png",
	RESOURCES__TEXTURES__STRINGS__TEAM2WIN_PNG: "res/resources/textures/Strings/Team2Win.png",
	RESOURCES__TEXTURES__TANK__TANK1SELECTED_PNG: "res/resources/textures/Tank/tank1Selected.png",
	RESOURCES__TEXTURES__TANK__TANK2SELECTED_PNG: "res/resources/textures/Tank/tank2Selected.png",
	RESOURCES__TEXTURES__TANK__TANK3SELECTED_PNG: "res/resources/textures/Tank/tank3Selected.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1A_PNG: "res/resources/textures/Tank/Team 1/1A.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1B_PNG: "res/resources/textures/Tank/Team 1/1B.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1C_PNG: "res/resources/textures/Tank/Team 1/1C.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1D_PNG: "res/resources/textures/Tank/Team 1/1D.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1S_PNG: "res/resources/textures/Tank/Team 1/1S.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2A_PNG: "res/resources/textures/Tank/Team 1/2A.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2B_PNG: "res/resources/textures/Tank/Team 1/2B.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2C_PNG: "res/resources/textures/Tank/Team 1/2C.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2D_PNG: "res/resources/textures/Tank/Team 1/2D.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2S_PNG: "res/resources/textures/Tank/Team 1/2S.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3A_PNG: "res/resources/textures/Tank/Team 1/3A.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3B_PNG: "res/resources/textures/Tank/Team 1/3B.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3C_PNG: "res/resources/textures/Tank/Team 1/3C.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3D_PNG: "res/resources/textures/Tank/Team 1/3D.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3S_PNG: "res/resources/textures/Tank/Team 1/3S.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1A_PNG: "res/resources/textures/Tank/Team 2/1A.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1B_PNG: "res/resources/textures/Tank/Team 2/1B.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1C_PNG: "res/resources/textures/Tank/Team 2/1C.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1D_PNG: "res/resources/textures/Tank/Team 2/1D.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1S_PNG: "res/resources/textures/Tank/Team 2/1S.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2A_PNG: "res/resources/textures/Tank/Team 2/2A.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2B_PNG: "res/resources/textures/Tank/Team 2/2B.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2C_PNG: "res/resources/textures/Tank/Team 2/2C.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2D_PNG: "res/resources/textures/Tank/Team 2/2D.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2S_PNG: "res/resources/textures/Tank/Team 2/2S.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3A_PNG: "res/resources/textures/Tank/Team 2/3A.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3B_PNG: "res/resources/textures/Tank/Team 2/3B.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3C_PNG: "res/resources/textures/Tank/Team 2/3C.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3D_PNG: "res/resources/textures/Tank/Team 2/3D.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3S_PNG: "res/resources/textures/Tank/Team 2/3S.png",
	RESOURCES__TEXTURES__UI__BGTOOLTIP_PNG: "res/resources/textures/UI/bgTooltip.png",
	RESOURCES__TEXTURES__UI__BG_ADVERTISE_PNG: "res/resources/textures/UI/bg_advertise.png",
	RESOURCES__TEXTURES__UI__FASTFORWARDBUTTON_PNG: "res/resources/textures/UI/FastForwardButton.png",
	RESOURCES__TEXTURES__UI__METALBOARD_PNG: "res/resources/textures/UI/MetalBoard.png",
	RESOURCES__TEXTURES__UI__REWINDBUTTON_PNG: "res/resources/textures/UI/RewindButton.png",
	SHADOW__SHADOW1_PNG: "res/shadow/shadow1.png",

};

var resImgList = [];
for(var key in resImg){
	resImgList.push(resImg[key]);
}