/**
*	Auto generate
**/

//todo define
var resImg = {
	
	PLIST__LOGIN_PNG: "res/plist/login.png",
	SHADOW__SHADOW1_PNG: "res/shadow/shadow1.png",
	RESOURCES__TEXTURES__UI__FASTFORWARDBUTTON_PNG: "res/resources/textures/UI/FastForwardButton.png",
	RESOURCES__TEXTURES__UI__METALBOARD_PNG: "res/resources/textures/UI/MetalBoard.png",
	RESOURCES__TEXTURES__UI__REWINDBUTTON_PNG: "res/resources/textures/UI/RewindButton.png",
	RESOURCES__TEXTURES__UI__BGTOOLTIP_PNG: "res/resources/textures/UI/bgTooltip.png",
	RESOURCES__TEXTURES__UI__BG_ADVERTISE_PNG: "res/resources/textures/UI/bg_advertise.png",
	RESOURCES__TEXTURES__STRINGS__DRAW_PNG: "res/resources/textures/Strings/Draw.png",
	RESOURCES__TEXTURES__STRINGS__TEAM2WIN_PNG: "res/resources/textures/Strings/Team2Win.png",
	RESOURCES__TEXTURES__STRINGS__BADDRAW_PNG: "res/resources/textures/Strings/BadDraw.png",
	RESOURCES__TEXTURES__STRINGS__TEAM1WIN_PNG: "res/resources/textures/Strings/Team1Win.png",
	RESOURCES__TEXTURES__STRINGS__STRINGTEMPLATE_PNG: "res/resources/textures/Strings/StringTemplate.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1B_PNG: "res/resources/textures/Tank/Team 2/1B.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1C_PNG: "res/resources/textures/Tank/Team 2/1C.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1A_PNG: "res/resources/textures/Tank/Team 2/1A.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1D_PNG: "res/resources/textures/Tank/Team 2/1D.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__1S_PNG: "res/resources/textures/Tank/Team 2/1S.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3C_PNG: "res/resources/textures/Tank/Team 2/3C.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3B_PNG: "res/resources/textures/Tank/Team 2/3B.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2S_PNG: "res/resources/textures/Tank/Team 2/2S.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2D_PNG: "res/resources/textures/Tank/Team 2/2D.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3A_PNG: "res/resources/textures/Tank/Team 2/3A.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2A_PNG: "res/resources/textures/Tank/Team 2/2A.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3S_PNG: "res/resources/textures/Tank/Team 2/3S.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__3D_PNG: "res/resources/textures/Tank/Team 2/3D.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2B_PNG: "res/resources/textures/Tank/Team 2/2B.png",
	RESOURCES__TEXTURES__TANK__TEAM___2__2C_PNG: "res/resources/textures/Tank/Team 2/2C.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1B_PNG: "res/resources/textures/Tank/Team 1/1B.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1C_PNG: "res/resources/textures/Tank/Team 1/1C.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1A_PNG: "res/resources/textures/Tank/Team 1/1A.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1D_PNG: "res/resources/textures/Tank/Team 1/1D.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__1S_PNG: "res/resources/textures/Tank/Team 1/1S.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3C_PNG: "res/resources/textures/Tank/Team 1/3C.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3B_PNG: "res/resources/textures/Tank/Team 1/3B.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2S_PNG: "res/resources/textures/Tank/Team 1/2S.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2D_PNG: "res/resources/textures/Tank/Team 1/2D.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3A_PNG: "res/resources/textures/Tank/Team 1/3A.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2A_PNG: "res/resources/textures/Tank/Team 1/2A.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3S_PNG: "res/resources/textures/Tank/Team 1/3S.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__3D_PNG: "res/resources/textures/Tank/Team 1/3D.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2B_PNG: "res/resources/textures/Tank/Team 1/2B.png",
	RESOURCES__TEXTURES__TANK__TEAM___1__2C_PNG: "res/resources/textures/Tank/Team 1/2C.png",
	RESOURCES__TEXTURES__SPLASH_PNG: "res/resources/textures/Splash.png",
	RESOURCES__TEXTURES__MAP__BRICK___1_PNG: "res/resources/textures/Map/Brick 1.png",
	RESOURCES__TEXTURES__MAP__BRICK___3_PNG: "res/resources/textures/Map/Brick 3.png",
	RESOURCES__TEXTURES__MAP__CONCRETE_PNG: "res/resources/textures/Map/Concrete.png",
	RESOURCES__TEXTURES__MAP__BRICK___2_PNG: "res/resources/textures/Map/Brick 2.png",
	RESOURCES__TEXTURES__MAP__BRICK___5_PNG: "res/resources/textures/Map/Brick 5.png",
	RESOURCES__TEXTURES__MAP__BRICK___4_PNG: "res/resources/textures/Map/Brick 4.png",
	RESOURCES__TEXTURES__MAP__BACKGROUND_PNG: "res/resources/textures/Map/Background.png",
	RESOURCES__TEXTURES__MAP__WATER_PNG: "res/resources/textures/Map/Water.png",
	RESOURCES__TEXTURES__MAP__BACKGROUND_1_PNG: "res/resources/textures/Map/Background_1.png",
	RESOURCES__TEXTURES__BULLET__2_PNG: "res/resources/textures/Bullet/2.png",
	RESOURCES__TEXTURES__BULLET__3_PNG: "res/resources/textures/Bullet/3.png",
	RESOURCES__TEXTURES__BULLET__1_PNG: "res/resources/textures/Bullet/1.png",
	RESOURCES__TEXTURES__EXPLOSION__8_PNG: "res/resources/textures/Explosion/8.png",
	RESOURCES__TEXTURES__EXPLOSION__4_PNG: "res/resources/textures/Explosion/4.png",
	RESOURCES__TEXTURES__EXPLOSION__5_PNG: "res/resources/textures/Explosion/5.png",
	RESOURCES__TEXTURES__EXPLOSION__7_PNG: "res/resources/textures/Explosion/7.png",
	RESOURCES__TEXTURES__EXPLOSION__6_PNG: "res/resources/textures/Explosion/6.png",
	RESOURCES__TEXTURES__EXPLOSION__2_PNG: "res/resources/textures/Explosion/2.png",
	RESOURCES__TEXTURES__EXPLOSION__3_PNG: "res/resources/textures/Explosion/3.png",
	RESOURCES__TEXTURES__EXPLOSION__1_PNG: "res/resources/textures/Explosion/1.png",
	RESOURCES__TEXTURES__POWERUP__AIRPLANE___1_PNG: "res/resources/textures/PowerUp/Airplane 1.png",
	RESOURCES__TEXTURES__POWERUP__AIRPLANE___2_PNG: "res/resources/textures/PowerUp/Airplane 2.png",
	RESOURCES__TEXTURES__POWERUP__EMP_PNG: "res/resources/textures/PowerUp/EMP.png",
	RESOURCES__TEXTURES__POWERUP__AIRSTRIKE_PNG: "res/resources/textures/PowerUp/Airstrike.png",
	RESOURCES__TEXTURES__PARTICLE__WHITESMOKE_PNG: "res/resources/textures/Particle/WhiteSmoke.png",
	RESOURCES__TEXTURES__PARTICLE__FRAG_PNG: "res/resources/textures/Particle/Frag.png",
	RESOURCES__TEXTURES__PARTICLE__BLACKSMOKE_PNG: "res/resources/textures/Particle/BlackSmoke.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__SIDEBASE_PNG: "res/resources/textures/Base/Team 2/SideBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__SIDEBASED_PNG: "res/resources/textures/Base/Team 2/SideBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__MAINBASED_PNG: "res/resources/textures/Base/Team 2/MainBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___2__MAINBASE_PNG: "res/resources/textures/Base/Team 2/MainBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__SIDEBASE_PNG: "res/resources/textures/Base/Team 1/SideBase.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__SIDEBASED_PNG: "res/resources/textures/Base/Team 1/SideBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__MAINBASED_PNG: "res/resources/textures/Base/Team 1/MainBaseD.png",
	RESOURCES__TEXTURES__BASE__TEAM___1__MAINBASE_PNG: "res/resources/textures/Base/Team 1/MainBase.png",
	DEFAULT__CHECKBOX_NORMAL_PNG: "res/Default/CheckBox_Normal.png",
	DEFAULT__IMAGEFILE_PNG: "res/Default/ImageFile.png",
	DEFAULT__CHECKBOXNODE_NORMAL_PNG: "res/Default/CheckBoxNode_Normal.png",
	DEFAULT__CHECKBOX_PRESS_PNG: "res/Default/CheckBox_Press.png",
	DEFAULT__CHECKBOX_DISABLE_PNG: "res/Default/CheckBox_Disable.png",
	DEFAULT__SPRITE_PNG: "res/Default/Sprite.png",
	DEFAULT__CHECKBOXNODE_DISABLE_PNG: "res/Default/CheckBoxNode_Disable.png",
	DEFAULT__BUTTON_PRESS_PNG: "res/Default/Button_Press.png",
	DEFAULT__BUTTON_NORMAL_PNG: "res/Default/Button_Normal.png",
	DEFAULT__BUTTON_DISABLE_PNG: "res/Default/Button_Disable.png",
	DEFAULT__LOADINGBARFILE_PNG: "res/Default/LoadingBarFile.png",
	NUMBER__STYLE2__8_PNG: "res/number/style2/8.png",
	NUMBER__STYLE2__9_PNG: "res/number/style2/9.png",
	NUMBER__STYLE2__4_PNG: "res/number/style2/4.png",
	NUMBER__STYLE2__5_PNG: "res/number/style2/5.png",
	NUMBER__STYLE2__7_PNG: "res/number/style2/7.png",
	NUMBER__STYLE2__6_PNG: "res/number/style2/6.png",
	NUMBER__STYLE2__2_PNG: "res/number/style2/2.png",
	NUMBER__STYLE2__3_PNG: "res/number/style2/3.png",
	NUMBER__STYLE2__1_PNG: "res/number/style2/1.png",
	NUMBER__STYLE2__0_PNG: "res/number/style2/0.png",
	NUMBER__STYLE3__PLUS_PNG: "res/number/style3/plus.png",
	NUMBER__STYLE3__8_PNG: "res/number/style3/8.png",
	NUMBER__STYLE3__9_PNG: "res/number/style3/9.png",
	NUMBER__STYLE3__DOT_PNG: "res/number/style3/dot.png",
	NUMBER__STYLE3__MINUS_PNG: "res/number/style3/minus.png",
	NUMBER__STYLE3__4_PNG: "res/number/style3/4.png",
	NUMBER__STYLE3__5_PNG: "res/number/style3/5.png",
	NUMBER__STYLE3__7_PNG: "res/number/style3/7.png",
	NUMBER__STYLE3__6_PNG: "res/number/style3/6.png",
	NUMBER__STYLE3__2_PNG: "res/number/style3/2.png",
	NUMBER__STYLE3__3_PNG: "res/number/style3/3.png",
	NUMBER__STYLE3__1_PNG: "res/number/style3/1.png",
	NUMBER__STYLE3__0_PNG: "res/number/style3/0.png",
	NUMBER__STYLE4__8_PNG: "res/number/style4/8.png",
	NUMBER__STYLE4__4_PNG: "res/number/style4/4.png",
	NUMBER__STYLE4__5_PNG: "res/number/style4/5.png",
	NUMBER__STYLE4__7_PNG: "res/number/style4/7.png",
	NUMBER__STYLE4__6_PNG: "res/number/style4/6.png",
	NUMBER__STYLE4__2_PNG: "res/number/style4/2.png",
	NUMBER__STYLE4__3_PNG: "res/number/style4/3.png",
	NUMBER__STYLE4__1_PNG: "res/number/style4/1.png",
	NUMBER__STYLE1__8_PNG: "res/number/style1/8.png",
	NUMBER__STYLE1__9_PNG: "res/number/style1/9.png",
	NUMBER__STYLE1__4_PNG: "res/number/style1/4.png",
	NUMBER__STYLE1__5_PNG: "res/number/style1/5.png",
	NUMBER__STYLE1__7_PNG: "res/number/style1/7.png",
	NUMBER__STYLE1__6_PNG: "res/number/style1/6.png",
	NUMBER__STYLE1__2_PNG: "res/number/style1/2.png",
	NUMBER__STYLE1__3_PNG: "res/number/style1/3.png",
	NUMBER__STYLE1__1_PNG: "res/number/style1/1.png",
	NUMBER__STYLE1__0_PNG: "res/number/style1/0.png",
	BUTTON__X2_PNG: "res/button/x2.png",
	BUTTON__X3_PNG: "res/button/x3.png",
	BUTTON__BUTTON_RECIEVEGIFT_PNG: "res/button/button_recieveGift.png",
	BUTTON__BACK_BTN_PNG: "res/button/back_btn.png",
	BUTTON__X_PNG: "res/button/x.png",
	BUTTON__BT_CHON_PNG: "res/button/bt_chon.png",
	BUTTON__BUTTON_BROWN_0_PNG: "res/button/button_brown_0.png",
	BUTTON__BTN_ORANGE_0_PNG: "res/button/btn_orange_0.png",
	BUTTON__BUTTON_GREEN_1_PNG: "res/button/button_green_1.png",
	BUTTON__CLOSENORMAL_PNG: "res/button/CloseNormal.png",
	BUTTON__BUTTON_GREEN_0_PNG: "res/button/button_green_0.png",
	BUTTON__BUTTON_GREEN_2_PNG: "res/button/button_green_2.png",
	BUTTON__BUTTON_GREEN_3_PNG: "res/button/button_green_3.png",
	BUTTON__BUTTON_QUICKCOMPLETE_PNG: "res/button/button_QuickComplete.png",
	BUTTON__BTN_BLUE_1_PNG: "res/button/btn_blue_1.png",
	BUTTON__BUTTON_YELLOW_2_PNG: "res/button/button_yellow_2.png",
	BUTTON__BUTTON_YELLOW_3_PNG: "res/button/button_yellow_3.png",
	BUTTON__BTN_BLUE_0_PNG: "res/button/btn_blue_0.png",
	BUTTON__BUTTON_YELLOW_1_PNG: "res/button/button_yellow_1.png",
	BUTTON__CLOSESELECTED_PNG: "res/button/CloseSelected.png",
	BUTTON__BUTTON_YELLOW_0_PNG: "res/button/button_yellow_0.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STAR_03_PNG: "res/particle/particle3d/textures/pump_star_03.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH09_PNG: "res/particle/particle3d/textures/anh09.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STAR_05_PNG: "res/particle/particle3d/textures/pump_star_05.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_RAIN_PNG: "res/particle/particle3d/textures/pu_rain.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_SMOKE_02_PNG: "res/particle/particle3d/textures/pump_smoke_02.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_02_PNG: "res/particle/particle3d/textures/pump_streak_02.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE01_PNG: "res/particle/particle3d/textures/bot_dice01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_03_PNG: "res/particle/particle3d/textures/pump_streak_03.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_RAIN_01_PNG: "res/particle/particle3d/textures/pu_rain_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_SNOW_01_PNG: "res/particle/particle3d/textures/pump_snow_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_01_PNG: "res/particle/particle3d/textures/pump_streak_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE02_PNG: "res/particle/particle3d/textures/bot_dice02.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE03_PNG: "res/particle/particle3d/textures/bot_dice03.png",
	PARTICLE__PARTICLE3D__TEXTURES__POINT04_PNG: "res/particle/particle3d/textures/point04.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_SPARK_01_PNG: "res/particle/particle3d/textures/pump_spark_01.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_STREAK_04_PNG: "res/particle/particle3d/textures/pump_streak_04.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE06_PNG: "res/particle/particle3d/textures/bot_dice06.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_FLARE_PNG: "res/particle/particle3d/textures/pu_flare.png",
	PARTICLE__PARTICLE3D__TEXTURES__RING2_PNG: "res/particle/particle3d/textures/ring2.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_BUBBLE_BLURRED_PNG: "res/particle/particle3d/textures/pump_bubble_blurred.png",
	PARTICLE__PARTICLE3D__TEXTURES__LOTUS_PNG: "res/particle/particle3d/textures/lotus.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE04_PNG: "res/particle/particle3d/textures/bot_dice04.png",
	PARTICLE__PARTICLE3D__TEXTURES__BOT_DICE05_PNG: "res/particle/particle3d/textures/bot_dice05.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_BUBBLE_PNG: "res/particle/particle3d/textures/pump_bubble.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH06_PNG: "res/particle/particle3d/textures/anh06.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH10_PNG: "res/particle/particle3d/textures/anh10.png",
	PARTICLE__PARTICLE3D__TEXTURES__PU_CIRCLE_PNG: "res/particle/particle3d/textures/pu_circle.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH04_PNG: "res/particle/particle3d/textures/anh04.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH05_PNG: "res/particle/particle3d/textures/anh05.png",
	PARTICLE__PARTICLE3D__TEXTURES__PUMP_FLARE_04_PNG: "res/particle/particle3d/textures/pump_flare_04.png",
	PARTICLE__PARTICLE3D__TEXTURES__TESTPU_PNG: "res/particle/particle3d/textures/testPU.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH02_PNG: "res/particle/particle3d/textures/anh02.png",
	PARTICLE__PARTICLE3D__TEXTURES__GOLD_PNG: "res/particle/particle3d/textures/gold.png",
	PARTICLE__PARTICLE3D__TEXTURES__ANH03_PNG: "res/particle/particle3d/textures/anh03.png",
	PARTICLE__TEST_PNG: "res/particle/test.png",
	PARTICLE__ELECTRICPOINT1_PNG: "res/particle/ElectricPoint1.png",
	PARTICLE__PARTICLE__FX_3_PNG: "res/particle/Particle/fx_3.png",
	PARTICLE__PARTICLE__FX_2_PNG: "res/particle/Particle/fx_2.png",
	PARTICLE__PARTICLE__PARTICLE_TEXTURE_PNG: "res/particle/Particle/particle_texture.png",
	PARTICLE__PARTICLE__FX_4H_PNG: "res/particle/Particle/fx_4h.png",
	PARTICLE__PARTICLE__FX_4L_PNG: "res/particle/Particle/fx_4l.png",
	PARTICLE__PARTICLE__FX_4M_PNG: "res/particle/Particle/fx_4m.png",
	PARTICLE__PARTICLE__FX_4N_PNG: "res/particle/Particle/fx_4n.png",

};

var resImgList = [];
for(var key in resImg){
	resImgList.push(resImg[key]);
}